CREATE TABLE levels
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT    NOT NULL UNIQUE,
    number       INTEGER NOT NULL UNIQUE,
    xp_threshold INTEGER NOT NULL
);

INSERT INTO levels (name, number, xp_threshold)
VALUES ('Новичок', 1, 0),
       ('Ученик', 2, 100),
       ('Опытный', 3, 250),
       ('Знаток', 4, 500),
       ('Профи', 5, 1000);