CREATE TABLE IF NOT EXISTS sections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    order_index INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS topics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL UNIQUE,
    xp_reward INTEGER NOT NULL,
    CONSTRAINT fk_topics_section FOREIGN KEY (section_id) REFERENCES sections (id)
);
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id INTEGER NOT NULL,
    type question_type NOT NULL,
    difficulty_level INTEGER NOT NULL,
    content JSONB NOT NULL,
    CONSTRAINT fk_questions_topic FOREIGN KEY (topic_id) REFERENCES topics (id)
);
CREATE TABLE IF NOT EXISTS answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    feedback TEXT NOT NULL,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id)
);
