CREATE TABLE users
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                  TEXT      NOT NULL UNIQUE,
    password_hash          TEXT      NOT NULL,
    name                   TEXT      NOT NULL,
    birth_date             TIMESTAMP NOT NULL,
    role                   user_role NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    level_id               INTEGER   NOT NULL default 1,
    current_xp             INTEGER   NOT NULL default 0,
    avatar_id              INTEGER   NOT NULL default 1,
    last_activity_date     TIMESTAMP,
    current_streak         INTEGER   NOT NULL default 0,
    is_leaderboard_visible BOOLEAN   NOT NULL,
    CONSTRAINT fk_users_level FOREIGN KEY (level_id) REFERENCES levels (id),
    CONSTRAINT fk_users_avatar FOREIGN KEY (avatar_id) REFERENCES avatars (id)
);
