CREATE TABLE IF NOT EXISTS achievements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    icon_url TEXT NOT NULL,
    requirements JSONB NOT NULL,
    reward_xp INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS user_achievements (
    user_id BIGINT NOT NULL,
    achievement_id INTEGER NOT NULL,
    earned_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, achievement_id),
    CONSTRAINT fk_user_achievements_achievement FOREIGN KEY (achievement_id) REFERENCES achievements (id)
);
CREATE TABLE IF NOT EXISTS user_metrics (
    user_id BIGINT NOT NULL,
    metric_code TEXT NOT NULL,
    value BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, metric_code)
);
