CREATE TYPE progress_status AS ENUM (
    'LOCKED',
    'UNLOCKED',
    'COMPLETED',
    'PENDING',
    'IN_PROGRESS',
    'FAILED'
    );

CREATE TYPE user_role AS ENUM (
    'ADMIN',
    'USER',
    'MODERATOR'
    );

CREATE TYPE question_type AS ENUM (
    'CHOICE',
    'MATCH'
    );

CREATE TYPE test_mode AS ENUM (
    'PRACTICE',
    'EXAM',
    'TOPIC',
    'SECTION'
    );

CREATE TYPE event_type AS ENUM();

CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email           TEXT      NOT NULL UNIQUE,
    password_hash   TEXT      NOT NULL,
    nickname        TEXT      NOT NULL,
    birth_date      TIMESTAMP NOT NULL,
    role            USER_ROLE NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    last_login_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS levels
(
    id           INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title        TEXT    NOT NULL UNIQUE,
    number       INTEGER NOT NULL UNIQUE,
    xp_threshold INTEGER NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS avatars
(
    id        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url       TEXT    NOT NULL UNIQUE,
    min_level INTEGER NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS achievements
(
    id           INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name         TEXT    NOT NULL UNIQUE,
    description  TEXT    NOT NULL,
    icon_url     TEXT    NOT NULL,
    requirements JSONB   NOT NULL,
    reward_xp    INTEGER NOT NULL,
    is_active    BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS user_achievements
(
    user_id        BIGINT    NOT NULL,
    achievement_id INTEGER   NOT NULL,
    earned_at      TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, achievement_id)
);



CREATE TABLE IF NOT EXISTS user_metrics
(
    user_id     BIGINT    NOT NULL,
    metric_code TEXT      NOT NULL,
    value       BIGINT    NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, metric_code)
);



CREATE TABLE IF NOT EXISTS sections
(
    id          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title       TEXT    NOT NULL,
    order_index INTEGER NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL,
    description TEXT    NOT NULL,
    url         TEXT    NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS topics
(
    id          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    section_id  INTEGER NOT NULL,
    title       TEXT    NOT NULL,
    content     JSONB   NOT NULL,
    order_index INTEGER NOT NULL UNIQUE,
    is_active   BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS questions
(
    id               BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    topic_id         INTEGER       NOT NULL,
    type             QUESTION_TYPE NOT NULL,
    difficulty_level INTEGER       NOT NULL,
    content          JSONB         NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS user_topic_progress
(
    user_id  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    topic_id INTEGER         NOT NULL,
    status   PROGRESS_STATUS NOT NULL,
    PRIMARY KEY (user_id, topic_id)
);



CREATE TABLE IF NOT EXISTS user_question_stats
(
    user_id             BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    question_id         BIGINT    NOT NULL,
    topic_id            INTEGER   NOT NULL,
    success_streak      INTEGER   NOT NULL,
    last_result_correct BOOLEAN   NOT NULL,
    next_review_at      TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, question_id)
);



CREATE TABLE IF NOT EXISTS review_intervals
(
    streak_level   INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    interval_hours INTEGER NOT NULL,
    PRIMARY KEY (streak_level)
);



CREATE TABLE IF NOT EXISTS user_section_progress
(
    user_id    BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    section_id INTEGER         NOT NULL,
    status     PROGRESS_STATUS NOT NULL,
    PRIMARY KEY (user_id, section_id)
);



CREATE TABLE IF NOT EXISTS game_profiles
(
    user_id                    BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    level_id                   INTEGER NOT NULL,
    avatar_id                  INTEGER NOT NULL,
    current_xp                 INTEGER NOT NULL,
    current_streak             INTEGER NOT NULL,
    last_activity_date         TIMESTAMP,
    total_active_days          INTEGER NOT NULL,
    is_leaderboard_participant BOOLEAN NOT NULL,
    PRIMARY KEY (user_id)
);



CREATE TABLE IF NOT EXISTS notifications
(
    id         BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT    NOT NULL,
    title      TEXT      NOT NULL,
    content    JSONB     NOT NULL,
    created_at TIMESTAMP NOT NULL,
    is_read    BOOLEAN   NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS test_sessions
(
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT          NOT NULL,
    topic_id        INTEGER,
    section_id      INTEGER,
    mode            TEST_MODE       NOT NULL,
    status          PROGRESS_STATUS NOT NULL,
    questions_data  JSONB           NOT NULL,
    total_questions INTEGER         NOT NULL,
    correct_count   INTEGER         NOT NULL,
    created_at      TIMESTAMP       NOT NULL,
    finished_at     TIMESTAMP,
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS pending_events
(
    id         BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type       EVENT_TYPE      NOT NULL,
    status     PROGRESS_STATUS NOT NULL,
    content    JSONB           NOT NULL,
    created_at TIMESTAMP       NOT NULL,
    PRIMARY KEY (id)
);



ALTER TABLE user_achievements
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_achievements
    ADD FOREIGN KEY (achievement_id) REFERENCES achievements (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_metrics
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE topics
    ADD FOREIGN KEY (section_id) REFERENCES sections (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE questions
    ADD FOREIGN KEY (topic_id) REFERENCES topics (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_question_stats
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_section_progress
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_topic_progress
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_topic_progress
    ADD FOREIGN KEY (topic_id) REFERENCES topics (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_section_progress
    ADD FOREIGN KEY (section_id) REFERENCES sections (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_question_stats
    ADD FOREIGN KEY (question_id) REFERENCES questions (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user_question_stats
    ADD FOREIGN KEY (topic_id) REFERENCES topics (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE notifications
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
-- (removed incorrect reverse FKs that referenced non-unique columns in game_profiles)
ALTER TABLE test_sessions
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE test_sessions
    ADD FOREIGN KEY (topic_id) REFERENCES topics (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE test_sessions
    ADD FOREIGN KEY (section_id) REFERENCES sections (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE game_profiles
    ADD FOREIGN KEY (level_id) REFERENCES levels (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE game_profiles
    ADD FOREIGN KEY (avatar_id) REFERENCES avatars (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE game_profiles
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE NO ACTION ON DELETE NO ACTION;