CREATE TABLE questions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id         INTEGER       NOT NULL,
    type             question_type NOT NULL,
    difficulty_level INTEGER       NOT NULL,
    content          JSONB         NOT NULL,
    CONSTRAINT fk_questions_topic FOREIGN KEY (topic_id) REFERENCES topics (id)
);
