CREATE TABLE topics
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id  INTEGER NOT NULL,
    name        TEXT    NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL UNIQUE,
    xp_reward   INTEGER NOT NULL,
    CONSTRAINT fk_topics_section FOREIGN KEY (section_id) REFERENCES sections (id)
);
