CREATE TABLE answers
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT  NOT NULL,
    text        TEXT    NOT NULL,
    is_correct  BOOLEAN NOT NULL,
    feedback    TEXT    NOT NULL,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id)
);
