CREATE TABLE user_sessions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    refresh_token_hash VARCHAR(255) NOT NULL UNIQUE,
    device_info        TEXT,
    expires_at         TIMESTAMP    NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
);