CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    title      TEXT      NOT NULL,
    content    JSONB     NOT NULL,
    created_at TIMESTAMP NOT NULL,
    is_read    BOOLEAN   NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
);

