CREATE TABLE test_sessions
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL,
    topic_id          INTEGER,
    section_id        INTEGER,
    mode              test_mode NOT NULL,
    status            progress_status NOT NULL,
    questions_data    JSONB     NOT NULL,
    total_quaestions  INTEGER   NOT NULL,
    correct_count     INTEGER   NOT NULL,
    created_at        TIMESTAMP NOT NULL,
    finished_at       TIMESTAMP,
    CONSTRAINT fk_test_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_test_sessions_topic FOREIGN KEY (topic_id) REFERENCES topics (id),
    CONSTRAINT fk_test_sessions_section FOREIGN KEY (section_id) REFERENCES sections (id)
);

