package ru.itmo.saferoad.gamification.domain;

public enum ActionType {
	SECTION_COMPLETED,
	ANSWER_STREAK,
	LOGIN_STREAK,
	DIFFICULTY_MASTER,
	EXPLORATION_COMPLETED,
	PERFECT_TEST,
	TOTAL_XP_REACHED,
	TOPIC_COMPLETED,
	SPECIAL_STATUS,
	TOPIC_PERFECT_RUN
}


