CREATE TYPE "Progress_Status" AS ENUM (
    'LOCKED',
    'UNLOCKED',
    'COMPLETED'
    );

CREATE TYPE "User_Role" AS ENUM (
    'ADMIN',
    'USER',
    'MODERATOR'
    );

CREATE TYPE "Question_Type" AS ENUM (
    'CHOICE',
    'MATCH'
    );

CREATE TYPE "Test_Mode" AS ENUM (
    'PRACTICE',
    'EXAM',
    'TOPIC',
    'SECTION'
    );

CREATE TYPE "Event_Type" AS ENUM (

    );

CREATE TABLE IF NOT EXISTS "Users" (
                                       "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       "email" TEXT NOT NULL UNIQUE,
                                       "password_hash" TEXT NOT NULL,
                                       "nickname" TEXT NOT NULL,
                                       "birth_date" TIMESTAMP NOT NULL,
                                       "role" USER_ROLE NOT NULL,
                                       "created_at" TIMESTAMP NOT NULL,
                                       "updated_at" TIMESTAMP NOT NULL,
                                       "last_login_date" TIMESTAMP NOT NULL,
                                       PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Levels" (
                                        "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        "title" TEXT NOT NULL UNIQUE,
                                        "number" INTEGER NOT NULL UNIQUE,
                                        "xp_threshold" INTEGER NOT NULL,
                                        PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Avatars" (
                                         "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         "url" TEXT NOT NULL UNIQUE,
                                         "min_level" INTEGER NOT NULL,
                                         PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Achievements" (
                                              "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              "name" TEXT NOT NULL UNIQUE,
                                              "description" TEXT NOT NULL,
                                              "icon_url" TEXT NOT NULL,
                                              "requirements" JSONB NOT NULL,
                                              "reward_xp" INTEGER NOT NULL,
                                              "is_active" BOOLEAN NOT NULL,
                                              PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "UserAchievements" (
                                                  "user_id" BIGINT NOT NULL,
                                                  "achievement_id" INTEGER NOT NULL,
                                                  "earned_at" TIMESTAMP NOT NULL,
                                                  PRIMARY KEY("user_id", "achievement_id")
);




CREATE TABLE IF NOT EXISTS "UserMetrics" (
                                             "user_id" BIGINT NOT NULL,
                                             "metric_code" TEXT NOT NULL,
                                             "value" BIGINT NOT NULL,
                                             "updated_at" TIMESTAMP NOT NULL,
                                             PRIMARY KEY("user_id", "metric_code")
);




CREATE TABLE IF NOT EXISTS "Sections" (
                                          "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "title" TEXT NOT NULL,
                                          "order_index" INTEGER NOT NULL UNIQUE,
                                          "is_active" BOOLEAN NOT NULL,
                                          PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Topics" (
                                        "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        "section_id" INTEGER NOT NULL,
                                        "title" TEXT NOT NULL,
                                        "content" JSONB NOT NULL,
                                        "order_index" INTEGER NOT NULL UNIQUE,
                                        "is_active" BOOLEAN NOT NULL,
                                        PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Questions" (
                                           "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                           "topic_id" INTEGER NOT NULL,
                                           "type" QUESTION_TYPE NOT NULL,
                                           "difficulty_level" INTEGER NOT NULL,
                                           "content" JSONB NOT NULL,
                                           PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "UserTopicProgress" (
                                                   "user_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   "topic_id" INTEGER NOT NULL,
                                                   "status" PROGRESS_STATUS NOT NULL,
                                                   PRIMARY KEY("user_id", "topic_id")
);




CREATE TABLE IF NOT EXISTS "UserQuestionStats" (
                                                   "user_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   "question_id" BIGINT NOT NULL,
                                                   "topic_id" INTEGER NOT NULL,
                                                   "success_streak" INTEGER NOT NULL,
                                                   "last_result_correct" BOOLEAN NOT NULL,
                                                   "next_review_at" TIMESTAMP NOT NULL,
                                                   PRIMARY KEY("user_id", "question_id")
);




CREATE TABLE IF NOT EXISTS "ReviewIntervals" (
                                                 "streak_level" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                 "interval_hours" INTEGER NOT NULL,
                                                 PRIMARY KEY("streak_level")
);




CREATE TABLE IF NOT EXISTS "UserSectionProgress" (
                                                     "user_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                     "section_id" INTEGER NOT NULL,
                                                     "status" PROGRESS_STATUS NOT NULL,
                                                     PRIMARY KEY("user_id", "section_id")
);




CREATE TABLE IF NOT EXISTS "GameProfiles" (
                                              "user_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              "level_id" INTEGER NOT NULL,
                                              "avatar_id" INTEGER NOT NULL,
                                              "current_xp" INTEGER NOT NULL,
                                              "current_streak" INTEGER NOT NULL,
                                              "last_activity_date" TIMESTAMP,
                                              "total_actie_days" INTEGER NOT NULL,
                                              "is_leaderboard_participant" BOOLEAN NOT NULL,
                                              PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "Notifications" (
                                               "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               "user_id" BIGINT NOT NULL,
                                               "title" TEXT NOT NULL,
                                               "content" JSONB NOT NULL,
                                               "created_at" TIMESTAMP NOT NULL,
                                               "is_read" BOOLEAN NOT NULL,
                                               PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "TestSessions" (
                                              "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              "user_id" BIGINT NOT NULL,
                                              "topic_id" INTEGER,
                                              "section_id" INTEGER,
                                              "mode" TEST_MODE NOT NULL,
                                              "status" PROGRESS_STATUS NOT NULL,
                                              "questions_data" JSONB NOT NULL,
                                              "total_quaestions" INTEGER NOT NULL,
                                              "correct_count" INTEGER NOT NULL,
                                              "created_at" TIMESTAMP NOT NULL,
                                              "finished_at" TIMESTAMP,
                                              PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "PendingEvents" (
                                               "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               "type" EVENT_TYPE NOT NULL,
                                               "status" PROGRESS_STATUS NOT NULL,
                                               "content" JSONB NOT NULL,
                                               PRIMARY KEY("id")
);



ALTER TABLE "UserAchievements"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserAchievements"
    ADD FOREIGN KEY("achievement_id") REFERENCES "Achievements"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserMetrics"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Topics"
    ADD FOREIGN KEY("section_id") REFERENCES "Sections"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Questions"
    ADD FOREIGN KEY("topic_id") REFERENCES "Topics"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserQuestionStats"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserSectionProgress"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserTopicProgress"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserTopicProgress"
    ADD FOREIGN KEY("topic_id") REFERENCES "Topics"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserSectionProgress"
    ADD FOREIGN KEY("section_id") REFERENCES "Sections"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserQuestionStats"
    ADD FOREIGN KEY("question_id") REFERENCES "Questions"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserQuestionStats"
    ADD FOREIGN KEY("topic_id") REFERENCES "Topics"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Notifications"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Levels"
    ADD FOREIGN KEY("id") REFERENCES "GameProfiles"("level_id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Avatars"
    ADD FOREIGN KEY("id") REFERENCES "GameProfiles"("avatar_id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "TestSessions"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "TestSessions"
    ADD FOREIGN KEY("topic_id") REFERENCES "Topics"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "TestSessions"
    ADD FOREIGN KEY("section_id") REFERENCES "Sections"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "GameProfiles"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;