CREATE TABLE achievements
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT    NOT NULL UNIQUE,
    description  TEXT    NOT NULL,
    icon_url     TEXT    NOT NULL,
    requirements JSONB   NOT NULL,
    reward_xp    INTEGER NOT NULL,
    is_active    BOOLEAN NOT NULL
);

